/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CategoriasRequestBuilderRequestsMetadata, type CategoriasRequestBuilder } from './categorias/index.js';
// @ts-ignore
import { TiposCorrespondenciaRequestBuilderRequestsMetadata, type TiposCorrespondenciaRequestBuilder } from './tiposCorrespondencia/index.js';
// @ts-ignore
import { TiposTransacaoRequestBuilderRequestsMetadata, type TiposTransacaoRequestBuilder } from './tiposTransacao/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/enums
 */
export interface EnumsRequestBuilder extends BaseRequestBuilder<EnumsRequestBuilder> {
    /**
     * The categorias property
     */
    get categorias(): CategoriasRequestBuilder;
    /**
     * The tiposCorrespondencia property
     */
    get tiposCorrespondencia(): TiposCorrespondenciaRequestBuilder;
    /**
     * The tiposTransacao property
     */
    get tiposTransacao(): TiposTransacaoRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const EnumsRequestBuilderUriTemplate = "{+baseurl}/api/enums";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const EnumsRequestBuilderNavigationMetadata: Record<Exclude<keyof EnumsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    categorias: {
        requestsMetadata: CategoriasRequestBuilderRequestsMetadata,
    },
    tiposCorrespondencia: {
        requestsMetadata: TiposCorrespondenciaRequestBuilderRequestsMetadata,
    },
    tiposTransacao: {
        requestsMetadata: TiposTransacaoRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
