/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { GeradoresRequestBuilderRequestsMetadata, type GeradoresRequestBuilder } from './geradores/index.js';
// @ts-ignore
import { ParsersRequestBuilderRequestsMetadata, type ParsersRequestBuilder } from './parsers/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/bancos
 */
export interface BancosRequestBuilder extends BaseRequestBuilder<BancosRequestBuilder> {
    /**
     * The geradores property
     */
    get geradores(): GeradoresRequestBuilder;
    /**
     * The parsers property
     */
    get parsers(): ParsersRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const BancosRequestBuilderUriTemplate = "{+baseurl}/api/bancos";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const BancosRequestBuilderNavigationMetadata: Record<Exclude<keyof BancosRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    geradores: {
        requestsMetadata: GeradoresRequestBuilderRequestsMetadata,
    },
    parsers: {
        requestsMetadata: ParsersRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
