/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createExtratoBancarioDtoFromDiscriminatorValue, type ExtratoBancarioDto } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/extratos/parse
 */
export interface ParseRequestBuilder extends BaseRequestBuilder<ParseRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ExtratoBancarioDto>}
     */
     post(body: ArrayBuffer | undefined, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ExtratoBancarioDto | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ArrayBuffer | undefined, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ParseRequestBuilderUriTemplate = "{+baseurl}/api/extratos/parse";
/**
 * Metadata for all the requests in the request builder.
 */
export const ParseRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ParseRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createExtratoBancarioDtoFromDiscriminatorValue,
        requestBodyContentType: "multipart/form-data",
        requestInformationContentSetMethod: "setStreamContent",
    },
};
/* tslint:enable */
/* eslint-enable */
