/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { serializeClassificarTransacoesRequest, type ClassificarTransacoesRequest } from '../../models/index.js';
// @ts-ignore
import { ExtratoRequestBuilderRequestsMetadata, type ExtratoRequestBuilder } from './extrato/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/classificacao
 */
export interface ClassificacaoRequestBuilder extends BaseRequestBuilder<ClassificacaoRequestBuilder> {
    /**
     * The extrato property
     */
    get extrato(): ExtratoRequestBuilder;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     post(body: ClassificarTransacoesRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ClassificarTransacoesRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ClassificacaoRequestBuilderUriTemplate = "{+baseurl}/api/classificacao";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ClassificacaoRequestBuilderNavigationMetadata: Record<Exclude<keyof ClassificacaoRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    extrato: {
        requestsMetadata: ExtratoRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ClassificacaoRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ClassificacaoRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeClassificarTransacoesRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
