/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { BancosRequestBuilderNavigationMetadata, type BancosRequestBuilder } from './bancos/index.js';
// @ts-ignore
import { ClassificacaoRequestBuilderNavigationMetadata, ClassificacaoRequestBuilderRequestsMetadata, type ClassificacaoRequestBuilder } from './classificacao/index.js';
// @ts-ignore
import { EnumsRequestBuilderNavigationMetadata, type EnumsRequestBuilder } from './enums/index.js';
// @ts-ignore
import { ExtratosRequestBuilderNavigationMetadata, type ExtratosRequestBuilder } from './extratos/index.js';
// @ts-ignore
import { PagamentosRequestBuilderNavigationMetadata, type PagamentosRequestBuilder } from './pagamentos/index.js';
// @ts-ignore
import { ReconciliacaoRequestBuilderRequestsMetadata, type ReconciliacaoRequestBuilder } from './reconciliacao/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The bancos property
     */
    get bancos(): BancosRequestBuilder;
    /**
     * The classificacao property
     */
    get classificacao(): ClassificacaoRequestBuilder;
    /**
     * The enums property
     */
    get enums(): EnumsRequestBuilder;
    /**
     * The extratos property
     */
    get extratos(): ExtratosRequestBuilder;
    /**
     * The pagamentos property
     */
    get pagamentos(): PagamentosRequestBuilder;
    /**
     * The reconciliacao property
     */
    get reconciliacao(): ReconciliacaoRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bancos: {
        navigationMetadata: BancosRequestBuilderNavigationMetadata,
    },
    classificacao: {
        requestsMetadata: ClassificacaoRequestBuilderRequestsMetadata,
        navigationMetadata: ClassificacaoRequestBuilderNavigationMetadata,
    },
    enums: {
        navigationMetadata: EnumsRequestBuilderNavigationMetadata,
    },
    extratos: {
        navigationMetadata: ExtratosRequestBuilderNavigationMetadata,
    },
    pagamentos: {
        navigationMetadata: PagamentosRequestBuilderNavigationMetadata,
    },
    reconciliacao: {
        requestsMetadata: ReconciliacaoRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
