/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter, type UntypedNode } from '@microsoft/kiota-abstractions';

export interface ClassificarTransacoesRequest extends AdditionalDataHolder, Parsable {
    /**
     * The transacoes property
     */
    transacoes?: TransacaoDto[] | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ClassificarTransacoesRequest}
 */
// @ts-ignore
export function createClassificarTransacoesRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoClassificarTransacoesRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ExtratoBancarioDto}
 */
// @ts-ignore
export function createExtratoBancarioDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoExtratoBancarioDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GerarPagamentoRequest}
 */
// @ts-ignore
export function createGerarPagamentoRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGerarPagamentoRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LancamentoERPDto}
 */
// @ts-ignore
export function createLancamentoERPDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLancamentoERPDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PagamentoDto}
 */
// @ts-ignore
export function createPagamentoDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPagamentoDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ReconciliarRequest}
 */
// @ts-ignore
export function createReconciliarRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoReconciliarRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TransacaoDto}
 */
// @ts-ignore
export function createTransacaoDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTransacaoDto;
}
/**
 * The deserialization information for the current model
 * @param ClassificarTransacoesRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoClassificarTransacoesRequest(classificarTransacoesRequest: Partial<ClassificarTransacoesRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "transacoes": n => { classificarTransacoesRequest.transacoes = n.getCollectionOfObjectValues<TransacaoDto>(createTransacaoDtoFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param ExtratoBancarioDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoExtratoBancarioDto(extratoBancarioDto: Partial<ExtratoBancarioDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "banco": n => { extratoBancarioDto.banco = n.getStringValue(); },
        "dataFim": n => { extratoBancarioDto.dataFim = n.getDateValue(); },
        "dataInicio": n => { extratoBancarioDto.dataInicio = n.getDateValue(); },
        "numeroConta": n => { extratoBancarioDto.numeroConta = n.getStringValue(); },
        "saldoFinal": n => { extratoBancarioDto.saldoFinal = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "saldoInicial": n => { extratoBancarioDto.saldoInicial = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "transacoes": n => { extratoBancarioDto.transacoes = n.getCollectionOfObjectValues<TransacaoDto>(createTransacaoDtoFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param GerarPagamentoRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGerarPagamentoRequest(gerarPagamentoRequest: Partial<GerarPagamentoRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "banco": n => { gerarPagamentoRequest.banco = n.getStringValue(); },
        "pagamentos": n => { gerarPagamentoRequest.pagamentos = n.getCollectionOfObjectValues<PagamentoDto>(createPagamentoDtoFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param LancamentoERPDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLancamentoERPDto(lancamentoERPDto: Partial<LancamentoERPDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "cliente": n => { lancamentoERPDto.cliente = n.getStringValue(); },
        "data": n => { lancamentoERPDto.data = n.getDateValue(); },
        "descricao": n => { lancamentoERPDto.descricao = n.getStringValue(); },
        "fornecedor": n => { lancamentoERPDto.fornecedor = n.getStringValue(); },
        "id": n => { lancamentoERPDto.id = n.getStringValue(); },
        "numeroDocumento": n => { lancamentoERPDto.numeroDocumento = n.getStringValue(); },
        "referencia": n => { lancamentoERPDto.referencia = n.getStringValue(); },
        "status": n => { lancamentoERPDto.status = n.getStringValue(); },
        "valor": n => { lancamentoERPDto.valor = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param PagamentoDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPagamentoDto(pagamentoDto: Partial<PagamentoDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "bancoBeneficiario": n => { pagamentoDto.bancoBeneficiario = n.getStringValue(); },
        "beneficiario": n => { pagamentoDto.beneficiario = n.getStringValue(); },
        "contaBeneficiario": n => { pagamentoDto.contaBeneficiario = n.getStringValue(); },
        "dataPagamento": n => { pagamentoDto.dataPagamento = n.getDateValue(); },
        "descricao": n => { pagamentoDto.descricao = n.getStringValue(); },
        "id": n => { pagamentoDto.id = n.getStringValue(); },
        "referencia": n => { pagamentoDto.referencia = n.getStringValue(); },
        "tipo": n => { pagamentoDto.tipo = n.getStringValue(); },
        "valor": n => { pagamentoDto.valor = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param ReconciliarRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoReconciliarRequest(reconciliarRequest: Partial<ReconciliarRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "lancamentosERP": n => { reconciliarRequest.lancamentosERP = n.getCollectionOfObjectValues<LancamentoERPDto>(createLancamentoERPDtoFromDiscriminatorValue); },
        "transacoes": n => { reconciliarRequest.transacoes = n.getCollectionOfObjectValues<TransacaoDto>(createTransacaoDtoFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param TransacaoDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTransacaoDto(transacaoDto: Partial<TransacaoDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "beneficiario": n => { transacaoDto.beneficiario = n.getStringValue(); },
        "categoria": n => { transacaoDto.categoria = n.getStringValue(); },
        "confiancaClassificacao": n => { transacaoDto.confiancaClassificacao = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "contaBancaria": n => { transacaoDto.contaBancaria = n.getStringValue(); },
        "data": n => { transacaoDto.data = n.getDateValue(); },
        "descricao": n => { transacaoDto.descricao = n.getStringValue(); },
        "documentoOrigem": n => { transacaoDto.documentoOrigem = n.getStringValue(); },
        "id": n => { transacaoDto.id = n.getStringValue(); },
        "referencia": n => { transacaoDto.referencia = n.getStringValue(); },
        "tipo": n => { transacaoDto.tipo = n.getStringValue(); },
        "valor": n => { transacaoDto.valor = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
    }
}
export interface ExtratoBancarioDto extends AdditionalDataHolder, Parsable {
    /**
     * The banco property
     */
    banco?: string | null;
    /**
     * The dataFim property
     */
    dataFim?: Date | null;
    /**
     * The dataInicio property
     */
    dataInicio?: Date | null;
    /**
     * The numeroConta property
     */
    numeroConta?: string | null;
    /**
     * The saldoFinal property
     */
    saldoFinal?: UntypedNode | null;
    /**
     * The saldoInicial property
     */
    saldoInicial?: UntypedNode | null;
    /**
     * The transacoes property
     */
    transacoes?: TransacaoDto[] | null;
}
export interface GerarPagamentoRequest extends AdditionalDataHolder, Parsable {
    /**
     * The banco property
     */
    banco?: string | null;
    /**
     * The pagamentos property
     */
    pagamentos?: PagamentoDto[] | null;
}
export interface LancamentoERPDto extends AdditionalDataHolder, Parsable {
    /**
     * The cliente property
     */
    cliente?: string | null;
    /**
     * The data property
     */
    data?: Date | null;
    /**
     * The descricao property
     */
    descricao?: string | null;
    /**
     * The fornecedor property
     */
    fornecedor?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The numeroDocumento property
     */
    numeroDocumento?: string | null;
    /**
     * The referencia property
     */
    referencia?: string | null;
    /**
     * The status property
     */
    status?: string | null;
    /**
     * The valor property
     */
    valor?: UntypedNode | null;
}
export interface PagamentoDto extends AdditionalDataHolder, Parsable {
    /**
     * The bancoBeneficiario property
     */
    bancoBeneficiario?: string | null;
    /**
     * The beneficiario property
     */
    beneficiario?: string | null;
    /**
     * The contaBeneficiario property
     */
    contaBeneficiario?: string | null;
    /**
     * The dataPagamento property
     */
    dataPagamento?: Date | null;
    /**
     * The descricao property
     */
    descricao?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The referencia property
     */
    referencia?: string | null;
    /**
     * The tipo property
     */
    tipo?: string | null;
    /**
     * The valor property
     */
    valor?: UntypedNode | null;
}
export interface ReconciliarRequest extends AdditionalDataHolder, Parsable {
    /**
     * The lancamentosERP property
     */
    lancamentosERP?: LancamentoERPDto[] | null;
    /**
     * The transacoes property
     */
    transacoes?: TransacaoDto[] | null;
}
/**
 * Serializes information the current object
 * @param ClassificarTransacoesRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeClassificarTransacoesRequest(writer: SerializationWriter, classificarTransacoesRequest: Partial<ClassificarTransacoesRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!classificarTransacoesRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<TransacaoDto>("transacoes", classificarTransacoesRequest.transacoes, serializeTransacaoDto);
    writer.writeAdditionalData(classificarTransacoesRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param ExtratoBancarioDto The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeExtratoBancarioDto(writer: SerializationWriter, extratoBancarioDto: Partial<ExtratoBancarioDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!extratoBancarioDto || isSerializingDerivedType) { return; }
    writer.writeStringValue("banco", extratoBancarioDto.banco);
    writer.writeDateValue("dataFim", extratoBancarioDto.dataFim);
    writer.writeDateValue("dataInicio", extratoBancarioDto.dataInicio);
    writer.writeStringValue("numeroConta", extratoBancarioDto.numeroConta);
    writer.writeObjectValue("saldoFinal", extratoBancarioDto.saldoFinal);
    writer.writeObjectValue("saldoInicial", extratoBancarioDto.saldoInicial);
    writer.writeCollectionOfObjectValues<TransacaoDto>("transacoes", extratoBancarioDto.transacoes, serializeTransacaoDto);
    writer.writeAdditionalData(extratoBancarioDto.additionalData);
}
/**
 * Serializes information the current object
 * @param GerarPagamentoRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGerarPagamentoRequest(writer: SerializationWriter, gerarPagamentoRequest: Partial<GerarPagamentoRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!gerarPagamentoRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("banco", gerarPagamentoRequest.banco);
    writer.writeCollectionOfObjectValues<PagamentoDto>("pagamentos", gerarPagamentoRequest.pagamentos, serializePagamentoDto);
    writer.writeAdditionalData(gerarPagamentoRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LancamentoERPDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLancamentoERPDto(writer: SerializationWriter, lancamentoERPDto: Partial<LancamentoERPDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!lancamentoERPDto || isSerializingDerivedType) { return; }
    writer.writeStringValue("cliente", lancamentoERPDto.cliente);
    writer.writeDateValue("data", lancamentoERPDto.data);
    writer.writeStringValue("descricao", lancamentoERPDto.descricao);
    writer.writeStringValue("fornecedor", lancamentoERPDto.fornecedor);
    writer.writeStringValue("id", lancamentoERPDto.id);
    writer.writeStringValue("numeroDocumento", lancamentoERPDto.numeroDocumento);
    writer.writeStringValue("referencia", lancamentoERPDto.referencia);
    writer.writeStringValue("status", lancamentoERPDto.status);
    writer.writeObjectValue("valor", lancamentoERPDto.valor);
    writer.writeAdditionalData(lancamentoERPDto.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PagamentoDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePagamentoDto(writer: SerializationWriter, pagamentoDto: Partial<PagamentoDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!pagamentoDto || isSerializingDerivedType) { return; }
    writer.writeStringValue("bancoBeneficiario", pagamentoDto.bancoBeneficiario);
    writer.writeStringValue("beneficiario", pagamentoDto.beneficiario);
    writer.writeStringValue("contaBeneficiario", pagamentoDto.contaBeneficiario);
    writer.writeDateValue("dataPagamento", pagamentoDto.dataPagamento);
    writer.writeStringValue("descricao", pagamentoDto.descricao);
    writer.writeStringValue("id", pagamentoDto.id);
    writer.writeStringValue("referencia", pagamentoDto.referencia);
    writer.writeStringValue("tipo", pagamentoDto.tipo);
    writer.writeObjectValue("valor", pagamentoDto.valor);
    writer.writeAdditionalData(pagamentoDto.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ReconciliarRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeReconciliarRequest(writer: SerializationWriter, reconciliarRequest: Partial<ReconciliarRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!reconciliarRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<LancamentoERPDto>("lancamentosERP", reconciliarRequest.lancamentosERP, serializeLancamentoERPDto);
    writer.writeCollectionOfObjectValues<TransacaoDto>("transacoes", reconciliarRequest.transacoes, serializeTransacaoDto);
    writer.writeAdditionalData(reconciliarRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TransacaoDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTransacaoDto(writer: SerializationWriter, transacaoDto: Partial<TransacaoDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!transacaoDto || isSerializingDerivedType) { return; }
    writer.writeStringValue("beneficiario", transacaoDto.beneficiario);
    writer.writeStringValue("categoria", transacaoDto.categoria);
    writer.writeObjectValue("confiancaClassificacao", transacaoDto.confiancaClassificacao);
    writer.writeStringValue("contaBancaria", transacaoDto.contaBancaria);
    writer.writeDateValue("data", transacaoDto.data);
    writer.writeStringValue("descricao", transacaoDto.descricao);
    writer.writeStringValue("documentoOrigem", transacaoDto.documentoOrigem);
    writer.writeStringValue("id", transacaoDto.id);
    writer.writeStringValue("referencia", transacaoDto.referencia);
    writer.writeStringValue("tipo", transacaoDto.tipo);
    writer.writeObjectValue("valor", transacaoDto.valor);
    writer.writeAdditionalData(transacaoDto.additionalData);
}
export interface TransacaoDto extends AdditionalDataHolder, Parsable {
    /**
     * The beneficiario property
     */
    beneficiario?: string | null;
    /**
     * The categoria property
     */
    categoria?: string | null;
    /**
     * The confiancaClassificacao property
     */
    confiancaClassificacao?: UntypedNode | null;
    /**
     * The contaBancaria property
     */
    contaBancaria?: string | null;
    /**
     * The data property
     */
    data?: Date | null;
    /**
     * The descricao property
     */
    descricao?: string | null;
    /**
     * The documentoOrigem property
     */
    documentoOrigem?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The referencia property
     */
    referencia?: string | null;
    /**
     * The tipo property
     */
    tipo?: string | null;
    /**
     * The valor property
     */
    valor?: UntypedNode | null;
}
/* tslint:enable */
/* eslint-enable */
