<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Simansoft.BridgeBank.Api</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Simansoft.BridgeBank.Api</AssemblyName>
    <OpenApiDocumentsDirectory>$(MSBuildProjectDirectory)/../../openapi</OpenApiDocumentsDirectory>
    <OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>
    <OpenApiGenerateDocumentsOnBuild>true</OpenApiGenerateDocumentsOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BridgeBank.Core\BridgeBank.Core.csproj" />
    <ProjectReference Include="..\BridgeBank.Parsers\BridgeBank.Parsers.csproj" />
    <ProjectReference Include="..\BridgeBank.Generators\BridgeBank.Generators.csproj" />
    <ProjectReference Include="..\BridgeBank.ML\BridgeBank.ML.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="10.0.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.13.18" />
  </ItemGroup>

</Project>
