/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { GerarRequestBuilderRequestsMetadata, type GerarRequestBuilder } from './gerar/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pagamentos
 */
export interface PagamentosRequestBuilder extends BaseRequestBuilder<PagamentosRequestBuilder> {
    /**
     * The gerar property
     */
    get gerar(): GerarRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PagamentosRequestBuilderUriTemplate = "{+baseurl}/api/pagamentos";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PagamentosRequestBuilderNavigationMetadata: Record<Exclude<keyof PagamentosRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    gerar: {
        requestsMetadata: GerarRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
