/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ParseRequestBuilderRequestsMetadata, type ParseRequestBuilder } from './parse/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/extratos
 */
export interface ExtratosRequestBuilder extends BaseRequestBuilder<ExtratosRequestBuilder> {
    /**
     * The parse property
     */
    get parse(): ParseRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ExtratosRequestBuilderUriTemplate = "{+baseurl}/api/extratos";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ExtratosRequestBuilderNavigationMetadata: Record<Exclude<keyof ExtratosRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    parse: {
        requestsMetadata: ParseRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
